name: mrx_icon_font_gen_example
description: >
  An example of project, where mrx_icon_font_gen tool was used to generate
  font-related files

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
   - family:  ChessIcons
     fonts:
      - asset: assets/fonts/ChessIcons.ttf
