name: mrx_icon_font_gen
description: A command-line application for generating an icon font from a set of SVG files using https://www.fluttericon.com
version: 0.1.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  lint: ^1.8.2
  test: ^1.21.1

dependencies:
  archive: ^3.3.0
  args: ^2.3.1
  crypto: ^3.0.2
  http: ^0.13.4
  path: ^1.8.2
  petitparser: ^5.0.0
  vector_math: ^2.1.2
  xml: ^6.1.0

executables:
  mrx_icon_font_gen: mrx_icon_font_gen
