name: icon_font
description: A command-line application for generating an icon font from a set of SVG files using https://www.fluttericon.com
version: 0.1.0

environment:
  sdk: '>=2.16.0 <3.0.0'

dev_dependencies:
  lints: any
  test: any

dependencies:
  archive: any
  args: any
  crypto: any
  http: any
  path: any
  petitparser: any
  vector_math: any
  xml: any

executables:
  icon_font: icon_font
